import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import FAQ from '@/app/components/FAQ';
import JsonLd from '@/app/components/JsonLd';
import { services, site } from '@/lib/site';

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)return {};return {title:s.name,description:s.short,alternates:{canonical:`/services/${s.slug}`},openGraph:{title:`${s.name} | Vorlen`,description:s.short,url:`${site.url}/services/${s.slug}`}}}
export default async function ServicePage({params}:Props){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site.url},{'@type':'ListItem',position:2,name:'Services',item:`${site.url}/services`},{'@type':'ListItem',position:3,name:s.name,item:`${site.url}/services/${s.slug}`}]};const serviceLd={'@context':'https://schema.org','@type':'Service',name:s.name,description:s.intro,url:`${site.url}/services/${s.slug}`,provider:{'@type':'Organization',name:'Vorlen',url:site.url},areaServed:['United Kingdom','Worldwide']};return <main id="main-content" className="subpage"><JsonLd data={[breadcrumb,serviceLd]}/><section className="service-hero"><Link className="back-link" href="/services"><ArrowLeft size={14}/> All services</Link><span className="section-num">Service / {s.number}</span><h1>{s.name}<span>.</span></h1><p>{s.intro}</p></section><section className="split-section"><div><span className="section-num">What changes</span><h2>Outcome before output.</h2></div><div className="outcome-list">{s.outcomes.map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div></section><section className="dark-detail"><div><span className="section-num">Typical scope</span><h2>What we can<br/><i>deliver.</i></h2></div><div className="deliverables">{s.deliverables.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></div>)}</div></section><section className="process-section"><span className="section-num">How it works</span><div className="process-grid"><article><span>01</span><h3>Understand</h3><p>Define the problem, audience, constraints, evidence and commercial objective.</p></article><article><span>02</span><h3>Shape</h3><p>Turn that understanding into structure, flows, content priorities and a clear direction.</p></article><article><span>03</span><h3>Build</h3><p>Design and engineer the experience with performance, accessibility and maintainability in mind.</p></article><article><span>04</span><h3>Improve</h3><p>Measure what matters, identify friction and evolve the system with evidence rather than guesswork.</p></article></div></section><section className="faq service-faq"><div className="section-num">Questions</div><h2>Useful<br/><i>answers.</i></h2><FAQ items={s.questions}/></section><section className="wide-cta"><p>Need {s.name.toLowerCase()}?</p><h2>Tell us what needs to change.</h2><Link className="button-dark" href="/contact">Start a project <ArrowUpRight size={17}/></Link></section></main>}
